CREATE TYPE "public"."difficulty" AS ENUM('easy', 'medium', 'hard');--> statement-breakpoint
CREATE TYPE "public"."file_processing_status" AS ENUM('pending', 'processing', 'completed', 'failed');--> statement-breakpoint
CREATE TYPE "public"."question_status" AS ENUM('draft', 'published', 'archived');--> statement-breakpoint
CREATE TYPE "public"."source_type" AS ENUM('file', 'url', 'text');--> statement-breakpoint
CREATE TABLE "pg-drizzle_account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_banca" (
	"id" varchar(50) PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text,
	"logo_url" text,
	"is_active" boolean NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_bookmark" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_bookmark_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"questionId" integer NOT NULL,
	"note" text,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_question_option" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_question_option_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"questionId" integer NOT NULL,
	"label" varchar(50) NOT NULL,
	"isCorrect" boolean NOT NULL,
	"displayOrder" integer NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_question" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_question_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"bancaId" varchar(50) NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"difficulty" "difficulty" NOT NULL,
	"status" "question_status" NOT NULL,
	"tags" jsonb,
	"generatedFromSourceIds" jsonb,
	"aiPrompt" text,
	"aiModel" varchar(100),
	"aiTokensUsed" integer,
	"explanation" text,
	"timesAnswered" integer NOT NULL,
	"correctAnswerRate" integer NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "pg-drizzle_session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_source" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_source_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"bancaId" varchar(50) NOT NULL,
	"type" "source_type" NOT NULL,
	"title" varchar(500) NOT NULL,
	"content" text,
	"url" text,
	"blobUrl" text,
	"blobKey" text,
	"fileName" varchar(500),
	"fileSize" integer,
	"mimeType" varchar(100),
	"processingStatus" "file_processing_status" NOT NULL,
	"processingError" text,
	"processedAt" timestamp with time zone,
	"extractedText" text,
	"metadata" jsonb,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean NOT NULL,
	"image" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "pg-drizzle_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_user_answer" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_user_answer_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"questionId" integer NOT NULL,
	"selectedOptionId" integer NOT NULL,
	"isCorrect" boolean NOT NULL,
	"timeSpentSeconds" integer,
	"answeredAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp
);
--> statement-breakpoint
ALTER TABLE "pg-drizzle_account" ADD CONSTRAINT "pg-drizzle_account_user_id_pg-drizzle_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."pg-drizzle_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_bookmark" ADD CONSTRAINT "pg-drizzle_bookmark_userId_pg-drizzle_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."pg-drizzle_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_bookmark" ADD CONSTRAINT "pg-drizzle_bookmark_questionId_pg-drizzle_question_id_fk" FOREIGN KEY ("questionId") REFERENCES "public"."pg-drizzle_question"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_post" ADD CONSTRAINT "pg-drizzle_post_createdById_pg-drizzle_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."pg-drizzle_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_question_option" ADD CONSTRAINT "pg-drizzle_question_option_questionId_pg-drizzle_question_id_fk" FOREIGN KEY ("questionId") REFERENCES "public"."pg-drizzle_question"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_question" ADD CONSTRAINT "pg-drizzle_question_userId_pg-drizzle_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."pg-drizzle_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_question" ADD CONSTRAINT "pg-drizzle_question_bancaId_pg-drizzle_banca_id_fk" FOREIGN KEY ("bancaId") REFERENCES "public"."pg-drizzle_banca"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_session" ADD CONSTRAINT "pg-drizzle_session_user_id_pg-drizzle_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."pg-drizzle_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_source" ADD CONSTRAINT "pg-drizzle_source_userId_pg-drizzle_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."pg-drizzle_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_source" ADD CONSTRAINT "pg-drizzle_source_bancaId_pg-drizzle_banca_id_fk" FOREIGN KEY ("bancaId") REFERENCES "public"."pg-drizzle_banca"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_user_answer" ADD CONSTRAINT "pg-drizzle_user_answer_userId_pg-drizzle_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."pg-drizzle_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_user_answer" ADD CONSTRAINT "pg-drizzle_user_answer_questionId_pg-drizzle_question_id_fk" FOREIGN KEY ("questionId") REFERENCES "public"."pg-drizzle_question"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_user_answer" ADD CONSTRAINT "pg-drizzle_user_answer_selectedOptionId_pg-drizzle_question_option_id_fk" FOREIGN KEY ("selectedOptionId") REFERENCES "public"."pg-drizzle_question_option"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "bookmark_user_idx" ON "pg-drizzle_bookmark" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "bookmark_question_idx" ON "pg-drizzle_bookmark" USING btree ("questionId");--> statement-breakpoint
CREATE INDEX "bookmark_user_question_unique_idx" ON "pg-drizzle_bookmark" USING btree ("userId","questionId");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "pg-drizzle_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "pg-drizzle_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "question_option_question_idx" ON "pg-drizzle_question_option" USING btree ("questionId");--> statement-breakpoint
CREATE INDEX "question_option_display_order_idx" ON "pg-drizzle_question_option" USING btree ("displayOrder");--> statement-breakpoint
CREATE INDEX "question_user_idx" ON "pg-drizzle_question" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "question_banca_idx" ON "pg-drizzle_question" USING btree ("bancaId");--> statement-breakpoint
CREATE INDEX "question_difficulty_idx" ON "pg-drizzle_question" USING btree ("difficulty");--> statement-breakpoint
CREATE INDEX "question_status_idx" ON "pg-drizzle_question" USING btree ("status");--> statement-breakpoint
CREATE INDEX "question_created_at_idx" ON "pg-drizzle_question" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "source_user_idx" ON "pg-drizzle_source" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "source_banca_idx" ON "pg-drizzle_source" USING btree ("bancaId");--> statement-breakpoint
CREATE INDEX "source_type_idx" ON "pg-drizzle_source" USING btree ("type");--> statement-breakpoint
CREATE INDEX "source_processing_status_idx" ON "pg-drizzle_source" USING btree ("processingStatus");--> statement-breakpoint
CREATE INDEX "user_answer_user_idx" ON "pg-drizzle_user_answer" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "user_answer_question_idx" ON "pg-drizzle_user_answer" USING btree ("questionId");--> statement-breakpoint
CREATE INDEX "user_answer_answered_at_idx" ON "pg-drizzle_user_answer" USING btree ("answeredAt");